
server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            #- After=2021-09-07T22:26:49.410+08:00[Asia/Shanghai]

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          filters:
          - AddRequestParameter=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id,值为1024
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #指定时间后才能访问（After）时间往后写一小时
            #            - After=2020-06-17T12:53:40.325+08:00[Asia/Shanghai]
            #指定时间前才能访问（Before）
            #            - Before=2020-06-17T11:53:40.325+08:00[Asia/Shanghai]
            #指定时间内才能访问（Between）
            #            - Between=2020-06-17T11:53:40.325+08:00[Asia/Shanghai],2020-06-17T12:53:40.325+08:00[Asia/Shanghai]
            #            - Cookie=username,angenin   #带Cookie，username的值为angenin
            #            - Header=X-Request-Id, \d+   #请求头要有 X-Request-Id属性并且值为整数的正则表达式
            #            - Host=**.angenin.com    #Host: xxx.angenin.com 请求是Host必须有**.angenin.com
            #            - Method=GET  #只允许get请求访问
            #            - Query=username, \d+   #url请求地址必须带上username参数，并且值必须为整数

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


